// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class D3Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void dEFECT1FUNHELLOTRAILING() {
    driver.get("https://cs1632.appspot.com/hello/");
    driver.manage().window().setSize(new Dimension(1600, 860));
    driver.findElement(By.linkText("Hello")).click();
    driver.findElement(By.cssSelector(".jumbotron")).click();
    assertEquals(vars.get("css=.jumbotron").toString(), "Hello CS1632, from #!");
  }
  @Test
  public void dEFECT2FUNINVALIDVALUE() {
    driver.get("https://cs1632.appspot.com/fact");
    driver.manage().window().setSize(new Dimension(1600, 860));
    driver.findElement(By.name("value")).sendKeys("n");
    driver.findElement(By.cssSelector("input:nth-child(2)")).click();
    driver.findElement(By.cssSelector("h1")).click();
    assertThat(driver.findElement(By.cssSelector("h1")).getText(), is("Factorial of n is 1!"));
  }
  @Test
  public void dEFECT3FUNINVALIDVALUE() {
    driver.get("https://cs1632.appspot.com/fact");
    driver.manage().window().setSize(new Dimension(1600, 860));
    driver.findElement(By.name("value")).click();
    driver.findElement(By.name("value")).sendKeys("2.0");
    driver.findElement(By.cssSelector("input:nth-child(2)")).click();
    driver.findElement(By.cssSelector("h1")).click();
    assertThat(driver.findElement(By.cssSelector("h1")).getText(), is("Factorial of 2.0 is 1!"));
  }
  @Test
  public void fUNCATHY() {
    driver.get("https://cs1632.appspot.com/cathy");
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("li:nth-child(1) > img"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("li:nth-child(3) > img"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("li:nth-child(5) > img"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("ol > li:nth-child(5)"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("ol > li:nth-child(3)"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("ol > li:nth-child(1)"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("li:nth-child(7) > img"));
      assert(elements.size() == 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("ol > li:nth-child(7)"));
      assert(elements.size() == 0);
    }
  }
  @Test
  public void fUNFACT() {
    driver.get("https://cs1632.appspot.com/");
    driver.manage().window().setSize(new Dimension(1600, 860));
    driver.findElement(By.linkText("Factorial")).click();
    driver.findElement(By.name("value")).click();
    driver.findElement(By.name("value")).sendKeys("5");
    driver.findElement(By.cssSelector("input:nth-child(2)")).click();
    driver.findElement(By.cssSelector("h2")).click();
    assertThat(driver.findElement(By.cssSelector("h2")).getText(), is("Factorial of 5 is 120!"));
  }
  @Test
  public void fUNFIB() {
    driver.get("https://cs1632.appspot.com/");
    driver.manage().window().setSize(new Dimension(1580, 840));
    driver.findElement(By.linkText("Fibonacci")).click();
    driver.findElement(By.name("value")).click();
    driver.findElement(By.name("value")).sendKeys("5");
    driver.findElement(By.cssSelector("input:nth-child(2)")).click();
    driver.findElement(By.cssSelector("h2")).click();
    assertThat(driver.findElement(By.cssSelector("h2")).getText(), is("Fibonacci of 5 is 5!"));
  }
  @Test
  public void fUNHELLO() {
    driver.get("https://cs1632.appspot.com/hello");
    driver.manage().window().setSize(new Dimension(1580, 840));
    driver.findElement(By.linkText("Hello")).click();
    driver.findElement(By.cssSelector("h2")).click();
    assertThat(driver.findElement(By.cssSelector("h2")).getText(), is("Hello CS1632, from Dr. Ahn!"));
  }
  @Test
  public void fUNHELLOTRAILING() {
    driver.get("https://cs1632.appspot.com/hello/Jazzy");
    driver.findElement(By.cssSelector("h2")).click();
    assertThat(driver.findElement(By.cssSelector("h2")).getText(), is("Hello CS1632, from Jazzy!"));
  }
  @Test
  public void fUNINVALIDVALUE() {
    driver.get("https://cs1632.appspot.com/");
    driver.manage().window().setSize(new Dimension(1580, 840));
    driver.findElement(By.linkText("Fibonacci")).click();
    driver.findElement(By.name("value")).click();
    driver.findElement(By.name("value")).sendKeys("-100");
    driver.findElement(By.cssSelector("input:nth-child(2)")).click();
    driver.findElement(By.cssSelector("h2")).click();
    assertThat(driver.findElement(By.cssSelector("h2")).getText(), is("Fibonacci of -100 is 1!"));
  }
  @Test
  public void fUNLINKS() {
    driver.get("https://cs1632.appspot.com/");
    driver.manage().window().setSize(new Dimension(1600, 860));
    vars.put("x", driver.findElements(By.xpath("//a")).size());
    assertEquals(vars.get("x").toString(), "5");
    vars.put("h", driver.findElement(By.linkText("CS1632 D3 Home")).getText());
    vars.put("fa", driver.findElement(By.linkText("Factorial")).getText());
    vars.put("fi", driver.findElement(By.linkText("Fibonacci")).getText());
    vars.put("he", driver.findElement(By.linkText("Hello")).getText());
    vars.put("c", driver.findElement(By.linkText("Cathedral Pics")).getText());
    assertEquals(vars.get("h").toString(), "CS1632 D3 Home");
    assertEquals(vars.get("fa").toString(), "Factorial");
    assertEquals(vars.get("fi").toString(), "Fibonacci");
    assertEquals(vars.get("he").toString(), "Hello");
    assertEquals(vars.get("c").toString(), "Cathedral Pics");
    driver.findElement(By.linkText("CS1632 D3 Home")).click();
    vars.put("val", js.executeScript("return window.location.href"));
    assertEquals(vars.get("val ").toString(), "https://cs1632.appspot.com/");
    driver.get("https://cs1632.appspot.com/fact");
    driver.manage().window().setSize(new Dimension(1600, 860));
    vars.put("x", driver.findElements(By.xpath("//a")).size());
    assertEquals(vars.get("x").toString(), "5");
    vars.put("h", driver.findElement(By.linkText("CS1632 D3 Home")).getText());
    vars.put("fa", driver.findElement(By.linkText("Factorial")).getText());
    vars.put("fi", driver.findElement(By.linkText("Fibonacci")).getText());
    vars.put("he", driver.findElement(By.linkText("Hello")).getText());
    vars.put("c", driver.findElement(By.linkText("Cathedral Pics")).getText());
    assertEquals(vars.get("h").toString(), "CS1632 D3 Home");
    assertEquals(vars.get("fa").toString(), "Factorial");
    assertEquals(vars.get("fi").toString(), "Fibonacci");
    assertEquals(vars.get("he").toString(), "Hello");
    assertEquals(vars.get("c").toString(), "Cathedral Pics");
    driver.findElement(By.linkText("Factorial")).click();
    vars.put("val", js.executeScript("return window.location.href"));
    assertEquals(vars.get("val ").toString(), "https://cs1632.appspot.com/fact");
    driver.get("https://cs1632.appspot.com/fib");
    driver.manage().window().setSize(new Dimension(1600, 860));
    vars.put("x", driver.findElements(By.xpath("//a")).size());
    assertEquals(vars.get("x").toString(), "5");
    vars.put("h", driver.findElement(By.linkText("CS1632 D3 Home")).getText());
    vars.put("fa", driver.findElement(By.linkText("Factorial")).getText());
    vars.put("fi", driver.findElement(By.linkText("Fibonacci")).getText());
    vars.put("he", driver.findElement(By.linkText("Hello")).getText());
    vars.put("c", driver.findElement(By.linkText("Cathedral Pics")).getText());
    assertEquals(vars.get("h").toString(), "CS1632 D3 Home");
    assertEquals(vars.get("fa").toString(), "Factorial");
    assertEquals(vars.get("fi").toString(), "Fibonacci");
    assertEquals(vars.get("he").toString(), "Hello");
    assertEquals(vars.get("c").toString(), "Cathedral Pics");
    driver.findElement(By.linkText("Fibonacci")).click();
    vars.put("val", js.executeScript("return window.location.href"));
    assertEquals(vars.get("val ").toString(), "https://cs1632.appspot.com/fib");
    driver.get("https://cs1632.appspot.com/hello");
    driver.manage().window().setSize(new Dimension(1600, 860));
    vars.put("x", driver.findElements(By.xpath("//a")).size());
    assertEquals(vars.get("x").toString(), "5");
    vars.put("h", driver.findElement(By.linkText("CS1632 D3 Home")).getText());
    vars.put("fa", driver.findElement(By.linkText("Factorial")).getText());
    vars.put("fi", driver.findElement(By.linkText("Fibonacci")).getText());
    vars.put("he", driver.findElement(By.linkText("Hello")).getText());
    vars.put("c", driver.findElement(By.linkText("Cathedral Pics")).getText());
    assertEquals(vars.get("h").toString(), "CS1632 D3 Home");
    assertEquals(vars.get("fa").toString(), "Factorial");
    assertEquals(vars.get("fi").toString(), "Fibonacci");
    assertEquals(vars.get("he").toString(), "Hello");
    assertEquals(vars.get("c").toString(), "Cathedral Pics");
    driver.findElement(By.linkText("Hello")).click();
    vars.put("val", js.executeScript("return window.location.href"));
    assertEquals(vars.get("val ").toString(), "https://cs1632.appspot.com/hello");
    driver.get("https://cs1632.appspot.com/cathy");
    driver.manage().window().setSize(new Dimension(1600, 860));
    vars.put("x", driver.findElements(By.xpath("//a")).size());
    assertEquals(vars.get("x").toString(), "5");
    vars.put("h", driver.findElement(By.linkText("CS1632 D3 Home")).getText());
    vars.put("fa", driver.findElement(By.linkText("Factorial")).getText());
    vars.put("fi", driver.findElement(By.linkText("Fibonacci")).getText());
    vars.put("he", driver.findElement(By.linkText("Hello")).getText());
    vars.put("c", driver.findElement(By.linkText("Cathedral Pics")).getText());
    assertEquals(vars.get("h").toString(), "CS1632 D3 Home");
    assertEquals(vars.get("fa").toString(), "Factorial");
    assertEquals(vars.get("fi").toString(), "Fibonacci");
    assertEquals(vars.get("he").toString(), "Hello");
    assertEquals(vars.get("c").toString(), "Cathedral Pics");
    driver.findElement(By.linkText("Cathedral Pics")).click();
    vars.put("val", js.executeScript("return window.location.href"));
    assertEquals(vars.get("val ").toString(), "https://cs1632.appspot.com/cathy");
  }
  @Test
  public void fUNWELCOME() {
    driver.get("https://cs1632.appspot.com");
    driver.manage().window().setSize(new Dimension(1600, 860));
    driver.findElement(By.cssSelector(".jumbotron ")).click();
    assertThat(driver.findElement(By.cssSelector(".jumbotron ")).getText(), is("Debugging is twice as hard as writing the code in the first place. Therefore, if you write the code as cleverly as possible, you are, by definition, not smart enough to debug it.\\\\n- Brian W. Kernighan"));
    assertThat(driver.getTitle(), is("CS1632 D3"));
  }
}
